### ISSUE TITLE
MACBOOK INTEL- Blender 3.0 stable python problem

### ISSUE THREAD

**Issue by ROYALKINGSJ** [daz3d/DazToBlender#108]
The MacBook with intel processor i am using.
and when i imports the model to blender there are some errors

Python: Traceback (most recent call last):
  File "/Users/safeshop/Library/Application Support/Blender/3.0/scripts/addons/DTB/DtbOperators.py", line 168, in invoke
    return self.execute(context)
  File "/Users/safeshop/Library/Application Support/Blender/3.0/scripts/addons/DTB/DtbOperators.py", line 349, in execute
    self.import_one(fbx_adr)
  File "/Users/safeshop/Library/Application Support/Blender/3.0/scripts/addons/DTB/DtbOperators.py", line 318, in import_one
    DtbIKBones.bone_disp(-1, True)
  File "/Users/safeshop/Library/Application Support/Blender/3.0/scripts/addons/DTB/DtbIKBones.py", line 346, in bone_disp
    bone_disp(i, flg_hide)
  File "/Users/safeshop/Library/Application Support/Blender/3.0/scripts/addons/DTB/DtbIKBones.py", line 351, in bone_disp
    bone_disp2(idx, pbones.get(ik_name[idx]),abones.get(ik_name[idx]), flg_hide)
  File "/Users/safeshop/Library/Application Support/Blender/3.0/scripts/addons/DTB/DtbIKBones.py", line 337, in bone_disp2
    pose_bone.custom_shape_scale = scales[idx]
AttributeError: 'PoseBone' object has no attribute 'custom_shape_scale'

location: <unknown location>:-1

 
please help

the character imported is perfect but i don't know why does it show errors in info logs in blender

**Comment by rafed1973** [comment]
Same issue with M1 apple silicon and Bender 3.0 as well.
I had to revert back to Blender 2.93 for the time being until this issue is resolved!

**Comment by ROYALKINGSJ** [comment]
> Same issue with M1 apple silicon and Bender 3.0 as well. I had to revert back to Blender 2.93 for the time being until this issue is resolved!

but what if you wanna use cycles-x and new features like geometry nodes and other stuff
