### ISSUE TITLE
To Rigify error

### ISSUE THREAD

**Issue by ADDRAIN1990** [daz3d/DazToBlender#115]
When I try to transfer it to rigify, following error happens:

Python: Traceback (most recent call last):
  File "C:\Users\joris\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\DTB\DtbOperators.py", line 438, in execute
    trf.toRigify(db, self)
  File "C:\Users\joris\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\DTB\ToRigify.py", line 92, in toRigify
    Global.bone_limit_modify()
TypeError: bone_limit_modify() missing 1 required positional argument: 'bone_limits'

**Comment by HWT-WalterHu** [comment]
I just encountered the seem issue, and fixed it by editing the mentioned line in  ToRigify.py (line 92 in your issue, maybe other lines in different version):
modify Global.bone_limit_modify() to **Global.bone_limit_modify([])** 

It happens because Global.bone_limit_modify function requires an empty list when bone_limits are empty

**Comment by Prototype-Zer0** [comment]
I am having a hard time getting this to work properly at least on Windows since it handles directories in a very strange way so you might end up with this error if you have way too many morphs.

```
    for file in os.listdir(Global.getHomeTown()):
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
```
