### ISSUE TITLE
I can't find to rigify button help (blender 3.1 ver)

### ISSUE THREAD

**Issue by choura95** [daz3d/DazToBlender#116]
![image](https://user-images.githubusercontent.com/101518147/158069514-dab6ce95-ec21-439f-b614-e2137777d648.png)

Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DTB\DtbOperators.py", line 168, in invoke
    return self.execute(context)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DTB\DtbOperators.py", line 349, in execute
    self.import_one(fbx_adr)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DTB\DtbOperators.py", line 318, in import_one
    DtbIKBones.bone_disp(-1, True)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DTB\DtbIKBones.py", line 346, in bone_disp
    bone_disp(i, flg_hide)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DTB\DtbIKBones.py", line 351, in bone_disp
    bone_disp2(idx, pbones.get(ik_name[idx]),abones.get(ik_name[idx]), flg_hide)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DTB\DtbIKBones.py", line 337, in bone_disp2
    pose_bone.custom_shape_scale = scales[idx]
AttributeError: 'PoseBone' object has no attribute 'custom_shape_scale'

location: <unknown location>:-1

**Comment by chlbrn** [comment]
This is normal and currently no fix since Daz to Blender bridge has not been update for over 6 months. I will stay with Blender 2.93 and wait more to see if official bridge has some progress.
