### ISSUE TITLE
trying to enable DAZ to Blender Mac osx in Blender traceback error 

### ISSUE THREAD

**Issue by davelebow** [daz3d/DazToBlender#139]
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.2/scripts/modules/addon_utils.py", line 371, in enable
    mod.register()
  File "/Users/davelebow/Library/Application Support/Blender/3.2/scripts/addons/DTB/__init__.py", line 319, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'CustomPathProperties'

**Comment by davelebow** [comment]
i would love some help if possible !

dave@davelebow.com

**Comment by danielbui78** [comment]
Can you launch Blender from a Terminal window and take a screenshot of the terminal after Blender finishes loading?  It should hopefully look something like this:
![Screenshot (131)](https://user-images.githubusercontent.com/11391924/180351071-6c22a66f-8d7e-4f81-9c6a-fc66df5530e3.png)

1. Also, please include what version of MacOS you are running
2. In the Blender Scripting Tab, inside the console tab, please copy and paste the PYTHON INTERACTIVE CONSOLE version number.
