### ISSUE TITLE
"WCmd is not defined".

### ISSUE THREAD

**Issue by Etarnalazure** [daz3d/DazToBlender#140]
Been looking everywhere on the internet to see what "WCmd" belongs to, however, I've found nothing except some stuff that mentions Python, however, installing the newest version didnt seem to fix this issue. So I figured I'd post here to see if this is a bigger issue:

Error:
Python: Traceback (most recent call last):
  File "G:\Steam\steamapps\common\Blender\2.93\scripts\addons\DTB\DtbCommands.py", line 22, in execute
    search_morph(context)
  File "G:\Steam\steamapps\common\Blender\2.93\scripts\addons\DTB\DtbCommands.py", line 39, in search_morph
    WCmd.Command(key[1:], context)
NameError: name 'WCmd' is not defined

location: <unknown location>:-1

How to replicate:
Try using the # commands mentioned in the guide PDF linked on Daz's forum, same error, no matter what follows the #

**Comment by danielbui78** [comment]
"WCmd" was actually the previous filename for "DtbCommands.py".  You can delete "WCmd." from line 39 to fix that bug.  I've done it in the file below.  We will include this change in a future patch.  Thanks.

[DtbCommands.zip](https://github.com/daz3d/DazToBlender/files/9190609/DtbCommands.zip)

Please Note: The PDF file that you are referring to is several years old and out of date.  Many features listed there have changed and will not work.  Can you please post a link to where you downloaded it from the forums?

**Comment by Etarnalazure** [comment]
I see you found it yourself :)
