### ISSUE TITLE
DTB 2.1.0 - Issue with IK not working when set from DazToBlender panel

### ISSUE THREAD

**Issue by andy-m-github** [daz3d/DazToBlender#15]
Hi,

My configuration is:

- Blender: 2.90
- DAZStudio: 4.12.1.118
- Bridge: 2.1.0

I've noticed that if IK mode is selected on any of rHand_IK, lHand_IK, rShin_IK or lShin_IK in the DazToBlender panel, that any movement of the corresponding bone in Pose mode will not work. That is, the bone will move, but the limb will not.

This appears to be due to the buttons on the panel not setting the Influence property in the Bone Constraint properties. If I manually set this to 1.0, the limb moves and to some extent tracks correctly until extreme positions are used, which can cause the limb to warp into an unnatural shape.

![image](https://user-images.githubusercontent.com/79371110/108779133-5813cb80-755e-11eb-8aac-390b5d8e3953.png)

I can see the functions that do this in __init__.py.

```
def set_ik(data_path):
    set_ik_influence(data_path, 1.0)

def set_fk(data_path):
    set_ik_influence(data_path, 0.0)

```

**Comment by andy-m-github** [comment]
A little extra info. This is output to the console.

```
Traceback (most recent call last):
  File "C:\Users\xxxxxxx\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DTB\__init__.py", line 1244, in ifk_update0
    ifk_update(context, 0)
  File "C:\Users\xxxxxxx\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DTB\__init__.py", line 1264, in ifk_update
    fktoik(idx)
  File "C:\Users\xxxxxxx\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DTB\__init__.py", line 1065, in fktoik
    manageKeyFrame(index, True, -1)
  File "C:\Users\xxxxxxx\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DTB\__init__.py", line 1012, in manageKeyFrame
    name = fcu.data_path.split(sep='"', maxsplit=2)[1]
IndexError: list index out of range
File "C:\Users\xxxxxxx\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DTB\__init__.py", line 1243, in ifk_update0

```

**Comment by samjay3d** [comment]
Thanks andy! We will take a look.

**Comment by samjay3d** [comment]
So, a few ways for IK to work right now. I will preface we still have kinks to deal with but, it's actually testable now. With the newest update if you uncheck the animations when exporting out of Daz you will get the rig working closest to what we expect. You can use it with animations but, issues are mainly with the IK Feet controls still. Let me know what you think :)

**Comment by samjay3d** [comment]
This issue has been fixed let us know if you find any more issues and we can reopen this issue.
