### ISSUE TITLE
Clear all pose error

### ISSUE THREAD

**Issue by Qwumpus** [daz3d/DazToBlender#158]
Python: Traceback (most recent call last):
  File "C:\Users\qbear\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\DTB\DtbOperators.py", line 447, in execute
    self.clear_pose()
  File "C:\Users\qbear\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\DTB\DtbOperators.py", line 443, in clear_pose
    bpy.ops.pose.transforms_clear()
  File "E:\Blender\3.4\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.pose.transforms_clear.poll() failed, context is incorrect

Error received after clicking clear all pose button.

**Comment by danielbui78** [comment]
Please let me know if the latest release https://github.com/daz3d/DazToBlender/releases/tag/2022.2.19.43 fixes your issue.

**Comment by danielbui78** [comment]
The latest bridge update should have fixed this bug.  If there are no other questions, I will close this issue.

Best Regards
