### ISSUE TITLE
 I dont have the character rigged but i do have the bones.

### ISSUE THREAD

**Issue by cris94Z** [daz3d/DazToBlender#166]
Every time i use the daz to blender bridge i always get this weird message:
    Versions.to_color_space_non(tex_image_node)
  File "C:\Users\cris9\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DTB\Versions.py", line 279, in to_color_space_non
    bpy.data.images[node.image.name].colorspace_settings.name = "Non-Color"
TypeError: bpy_struct: item.attr = val: enum "Non-Color" not found in ('2.2 EOTF Encoding', '2.4 EOTF Encoding', 'AgX Base', 'AgX Base BT.1886', 'AgX Base Display P3', 'AgX Log (Kraken)', 'Appearance Golden BT.1886', 'Appearance Golden Display P3', 'Appearance Golden sRGB', 'Appearance Punchy BT.1886', 'Appearance Punchy Display P3', 'Appearance Punchy sRGB', 'BT.1886', 'Display P3', 'Generic Data', 'Linear BT.709', 'sRGB')
Error: Python: Traceback (most recent call last):
  File "C:\Users\cris9\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DTB\DtbOperators.py", line 359, in execute
    self.import_one(fbx_adr)
  File "C:\Users\cris9\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DTB\DtbOperators.py", line 251, in import_one
    dtb_shaders.setup_materials(body)
  File "C:\Users\cris9\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DTB\DtbMaterial.py", line 451, in setup_materials
    self.create_texture_input(property_info, tex_image_node)
  File "C:\Users\cris9\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DTB\DtbMaterial.py", line 345, in create_texture_input
    Versions.to_color_space_non(tex_image_node)
  File "C:\Users\cris9\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DTB\Versions.py", line 279, in to_color_space_non
    bpy.data.images[node.image.name].colorspace_settings.name = "Non-Color"
TypeError: bpy_struct: item.attr = val: enum "Non-Color" not found in ('2.2 EOTF Encoding', '2.4 EOTF Encoding', 'AgX Base', 'AgX Base BT.1886', 'AgX Base Display P3', 'AgX Log (Kraken)', 'Appearance Golden BT.1886', 'Appearance Golden Display P3', 'Appearance Golden sRGB', 'Appearance Punchy BT.1886', 'Appearance Punchy Display P3', 'Appearance Punchy sRGB', 'BT.1886', 'Display P3', 'Generic Data', 'Linear BT.709', 'sRGB')

Also my character doesn't import the morphs, and it isn't rigged, but i do have the bones

**Comment by chlbrn** [comment]
Did you try importing default genesis character to test? I don't have any importing issues with my own character using latest bridge.

**Comment by kofiskofis** [comment]
I had the same issue but after installing python on the system and reimporting, the error disappeared.
