### ISSUE TITLE
Converting daz rig to Rigify error in Blender 4.0

### ISSUE THREAD

**Issue by totalvectors** [daz3d/DazToBlender#186]
Running the "To Rigify" operator in Blender generates this error in the console:

 Python: Traceback (most recent call last):
  File "C:\Users\total\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DTB\DtbOperators.py", line 565, in execute
    trf.toRigify(db, self)
  File "C:\Users\total\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DTB\ToRigify.py", line 163, in toRigify
    self.omit_g8(db)
  File "C:\Users\total\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DTB\ToRigify.py", line 248, in omit_g8
    self.to_layer(eb, 15)
  File "C:\Users\total\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DTB\ToRigify.py", line 281, in to_layer
    ebone.layers[lnum] = True
AttributeError: 'EditBone' object has no attribute 'layers'

Rigify rig is created but does not seem to be parented to the mesh. This happens even on the base genesis 8 character with no morphs. Has anyone else run across such an error? Have I messed up something in my installation? Everything seems to come over fine from Daz I just can'y convert the rig to Rigify. 

I know that Blender 4.0 isn't officially supported yet. Could the changes made to the rigging in 4.0 (change to bone collections) have something to do with this? Or is this an issue on Rigify's end?

**Comment by BonnieBon23** [comment]
Tengo el mismo problema :,( Me estoy volviendo loca
