### ISSUE TITLE
The new plugin doesn't work

### ISSUE THREAD

**Issue by MaarVFX** [daz3d/DazToBlender#32]
I have upgraded to the latest version 2.3.1
Like in the title... After exporting Genesis 2 char and moving to blender the plugin imports... nothing
It worked fine before the upgrade

please help

thanks

**Comment by TarouMaso** [comment]
![image](https://user-images.githubusercontent.com/8605767/114281308-e88a6a80-9a3d-11eb-8500-10cac9acab3c.png)

I get this error message. The model appears normally but I can't pose it. The morphs work.

**Comment by ludwj** [comment]
#31 



Python: Traceback (most recent call last):
  File "C:\Users\ludwj\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\DTB\DtbOperators.py", line 112, in invoke
    return self.execute(context)
  File "C:\Users\ludwj\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\DTB\DtbOperators.py", line 275, in execute
    self.import_one(fbx_adr)
  File "C:\Users\ludwj\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\DTB\DtbOperators.py", line 187, in import_one
    dtb_shaders.setup_materials(body)
  File "C:\Users\ludwj\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\DTB\DtbMaterial.py", line 394, in setup_materials
    shader_node.node_tree = bpy.data.node_groups[node_group]
KeyError: 'bpy_prop_collection[key]: key "IrayUberSkin" not found'

location: <unknown location>:-1

**Comment by MaarVFX** [comment]
Thanks for getting back to me!
I'm not sure what happened, but today, when I try to send my Genesis 2 Female it goes seamlessly - even the error doesn't come up!
Thanks again!
