### ISSUE TITLE
Error when trying to import environments/props

### ISSUE THREAD

**Issue by joneienleah** [daz3d/DazToBlender#56]
I am a very new user to Blender. I have created a simple scene with animation in Daz (empty room, Gen 8.1 figure, clothing in obj seq I created in CLO3D, and runway walk animation). The whole thing works fine in Daz, have even rendered it out. But I wanted to try rendering the animation and scene in Blender to cut down on rendering time. I am using the Daz to Blender bridge. Export from Daz seems to work okay. Import into Blender is the tricky part. If I click on import new Gen character, she loads in fine, but is missing her clothing, the environment & the animation seems to come in but doesn't actually do anything when I hit play.
If I click import new environment/props I get the error message below. No idea what I am doing wrong or if it is a bug. Please help.

Python: Traceback (most recent call last):
  File "C:\Users\jonei\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DTB\DtbOperators.py", line 305, in execute
    Environment.EnvProp()
  File "C:\Users\jonei\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DTB\Environment.py", line 34, in __init__
    self.execute()
  File "C:\Users\jonei\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DTB\Environment.py", line 56, in execute
    ReadFbx(os.path.join(self.env_root, 'ENV' + str(i)), i, int_progress)
  File "C:\Users\jonei\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DTB\Environment.py", line 84, in __init__
    if self.read_fbx():
  File "C:\Users\jonei\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DTB\Environment.py", line 94, in read_fbx
    objs = self.convert_file(adr)
  File "C:\Users\jonei\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DTB\Environment.py", line 154, in convert_file
    use_prepost_rot = False
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Couldn't open file 'C:\\Users\\jonei\\Documents\\DAZ 3D\\Bridges\\Daz To Blender\\Exports\\ENV\\ENV2\\B_ENV.fbx' (16)

location: <unknown location>:-1

**Comment by Popinjayishuman** [comment]
This seems to be a permission issue within blender. A quick check would be to change the export directory. you can find this in Import settings on the sidebar under DaztoBlender. Go to Auto Import settings and check 'use custom import path' click the folder icon to chose your dialogue and then press save config. Now your exports will go to the location you defined. Hope that works, let us know if there are any other issues.
