### ISSUE TITLE
Error on import in Blender ,DTB version 2.3.7

### ISSUE THREAD

**Issue by ForAiurSK** [daz3d/DazToBlender#64]
Hello,
For some reason , I forced closing Daz3d when DTB was sending data . Then I updated DTB to 2.3.7 and sent data . when I used blender for import model , I encountered the Errors . I tried to delete the file and Reinstall DTB , but the error still existed . I don't know the reason of error and how to deal with it . Could you please check and help me ?blender version is 2.83 .
Thank you.
![error1](https://user-images.githubusercontent.com/28665355/120900006-29c98000-c665-11eb-8b19-273b107052e4.png)
![error2](https://user-images.githubusercontent.com/28665355/120900036-54b3d400-c665-11eb-9224-89c3f7f30706.png)
Traceback (most recent call last):
File "C:\Users\QJF\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\DTB\DtbOperators.py", line 309, in execute
self.import_one(fbx_adr)
File "C:\Users\QJF\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\DTB\DtbOperators.py", line 196, in import_one
reload_dropdowns("choose_daz_figure")
File "C:\Users\QJF\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\DTB\DtbOperators.py", line 32, in reload_dropdowns
prop = Versions.get_properties(w_mgr.choose_daz_figure)
File "C:\Users\QJF\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\DTB\Versions.py", line 33, in get_properties
prop = dropdown.keywords
AttributeError: 'tuple' object has no attribute 'keywords'

location: :-1

**Comment by samjay3d** [comment]
https://github.com/daz3d/DazToBlender/releases/tag/2.3.9-beta
This has been fixed in the newest prerelease thank you for bring this to our attention.
